apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pparegrpa-go 
  janus-idp.io/tekton: pparegrpa-go
  backstage.io/kubernetes-id: pparegrpa-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pparegrpa-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml